GET http://localhost:3000/cats
###
GET http://localhost:3000/cats/1

###

POST http://localhost:3000/cats
Content-Type: application/json

{
  "name": "doug",
  "species": "bulldog",
  "age": 8
}

###

PATCH http://localhost:3000/cats/4
Content-Type: application/json

{
  "name": "dougy"
}

###

DELETE http://localhost:3000/cats/4

### 
GET http://localhost:3000/foods
